name: Build Latex PDF
on: [push]
jobs:
  build-pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: Satzung.tex
      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: Satzung.pdf
